openapi: 3.0.0
info:
  title: My API
  version: 1.0.0

# The routes on your API
paths:
    /hello:
        # GET /hello
        get:
            operationId: greet
            responses:
                '200': # When the request is successful
                    description: A hello message
                    content:
                        application/json:
                            schema: # The returned JSON object
                                type: object
                                properties:
                                    message:
                                        type: string
                                required:
                                    - message